### PR TITLE
Regen api

### PR DESCRIPTION
**Pull request by friederbluemle**
Generated files regenerated with newer version of ERN (primarily changing package names to all lowercase).

### CODE REVIEW

**Review by rthic23 — APPROVED** [review]
lgtm

**Comment by deepueg** [comment]
This may cause issues for existing apis that gets regenerated with the latest version of ern. I believe the package names in java are case sensitive.  Perhaps add this to release notes to avoid confusion.

**Comment by friederbluemle** [comment]
Thanks @deepueg for the comment! Yes, we also considered this - Since we are planning a few updates related to supporting newer versions of React Native (by @Karthiccc23) and some of them are breaking (e.g. androidx changes), the plan is to use a major version increment for the next release. I still had this old commit from December 2020 on a local branch which waited for this opportunity 😅 Per multiple conventions upper case characters in package names are not allowed, so now would be a good time to fix this and regenerate the API. The PR in the ERN platform repo that lower cases package names was merged as part of https://github.com/electrode-io/electrode-native/pull/1733 more than 2 years ago!

Btw unrelated question: Do you happen to remember how/why version `1.4.0` is available on npmjs.com? There are no traces of it in the repo...
https://www.npmjs.com/package/ernnavigation-api/v/1.4.0

**Comment by deepueg** [comment]
>
sounds good. 

 I don't remember exactly.   any changes we make to navigation-api needs to be published and if 1.4.0 is not found in GitHub, my guess is, that might have been a miss due to a manual release :-(.

**Pull request merged**
