### PR TITLE
New features

### PR DESCRIPTION
**Pull request by deepueg**
This PR adds two new features to ern-navigation-api.
1. `showAsOverlay` flag inside `ErnNavRoute` object. This allows MiniApps to show one component as an Overlay and still control the navigation bat behavior. 
2. Add `NavigationBarLeftButton` to the `NavigationBar` object. This enables left navigation bar customization.

### CODE REVIEW

**Comment by friederbluemle** [comment]
Any chance we can have the formatting cleanups and new features in two separate commits for easier review? :)

**Comment by deepueg** [comment]
Sure, will do.!

**Comment by deepueg** [comment]
@friederbluemle done.

**Review by friederbluemle — APPROVED** [review]
Cool, LGTM 👍 
How can I test this?

**Comment by deepueg** [comment]
I tested it by locally publishing it and using it inside [impl](https://github.com/electrode-io/ernnavigation-api-impl-native) project

**Review by asharpbflat — APPROVED** [review]
🎉

**Pull request merged**
